#!/usr/bin/env bash

set -euo pipefail

INPUT_SCALE="${1:-}"
INPUT_MONITOR_SCALE="${2:-}"
INPUT_SCALE_MODE="${3:-}"
LOG_DIR="${HOME}/__home_organized/logs"
RUNTIME_DIR="${HOME}/__home_organized/runtime/hypr-scaling"
LOG_FILE="${LOG_DIR}/hypr-app-scaling.log"
STATE_FILE="${RUNTIME_DIR}/current.env"
XRESOURCES_FILE="${RUNTIME_DIR}/xresources.scale"
GTK3_SETTINGS="${HOME}/.config/gtk-3.0/settings.ini"
GTK4_SETTINGS="${HOME}/.config/gtk-4.0/settings.ini"
KITTY_SCALE_CONF="${HOME}/.config/kitty/scale-generated.conf"
HYPRCURSOR_THEME="${HYPRCURSOR_THEME:-Bibata-Modern-Ice}"

mkdir -p "${LOG_DIR}" "${RUNTIME_DIR}"

log() {
  printf '%s %s\n' "$(date '+%F %T')" "$*" >>"${LOG_FILE}"
}

require_command() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    printf '%s is required\n' "${cmd}" >&2
    exit 1
  fi
}

get_current_scale() {
  hyprctl monitors -j | jq -r 'map(select(.focused))[0].scale // .[0].scale // empty' | awk 'NR==1 { printf "%.2f", $1 }'
}

update_ini_setting() {
  local file="$1"
  local key="$2"
  local value="$3"

  mkdir -p "$(dirname "${file}")"
  if [[ ! -f "${file}" ]]; then
    printf '[Settings]\n%s=%s\n' "${key}" "${value}" >"${file}"
    return
  fi

  if grep -q "^${key}=" "${file}"; then
    sed -i "s/^${key}=.*/${key}=${value}/" "${file}"
  else
    printf '%s=%s\n' "${key}" "${value}" >>"${file}"
  fi
}

require_command hyprctl
require_command jq
require_command awk

scale="${INPUT_SCALE}"
if [[ -z "${scale}" ]]; then
  if [[ -f "${STATE_FILE}" ]]; then
    # Restore sub-1.0 pseudo scaling across logins. The monitor itself remains
    # at 1.00, so the saved app scale is the source of truth for that mode.
    source "${STATE_FILE}"
    if [[ "${HYPR_SCALE_MODE:-}" == "pseudo" && -n "${HYPR_APP_SCALE:-}" ]]; then
      scale="${HYPR_APP_SCALE}"
    fi
  fi
fi

monitor_scale="${INPUT_MONITOR_SCALE}"
if [[ -z "${monitor_scale}" ]]; then
  monitor_scale="$(get_current_scale)"
fi

if [[ -z "${scale}" || "${scale}" == "null" ]]; then
  scale="${monitor_scale}"
fi

if [[ -z "${scale}" || "${scale}" == "null" ]]; then
  printf 'unable to determine the active Hyprland scale\n' >&2
  exit 1
fi

if [[ -z "${monitor_scale}" || "${monitor_scale}" == "null" ]]; then
  monitor_scale="${scale}"
fi

scale="$(awk -v value="${scale}" 'BEGIN { printf "%.2f", value + 0 }')"
monitor_scale="$(awk -v value="${monitor_scale}" 'BEGIN { printf "%.2f", value + 0 }')"
scale_mode="${INPUT_SCALE_MODE:-monitor}"
xft_dpi="$(awk -v value="${scale}" 'BEGIN { printf "%d", (96 * value) + 0.5 }')"
gtk_xft_dpi=$(( xft_dpi * 1024 ))
cursor_size="$(awk -v value="${scale}" 'BEGIN { printf "%d", (24 * value) + 0.5 }')"
kitty_font_size="$(awk -v value="${scale}" 'BEGIN { printf "%.1f", 16 * value }')"
kitty_padding="$(awk -v value="${scale}" 'BEGIN { padding = int((4 * value) + 0.5); if (padding < 4) padding = 4; printf "%d", padding }')"
qt_x11_scale="${scale}"
chrome_scale="${scale}"

cat >"${STATE_FILE}" <<EOF
HYPR_APP_SCALE='${scale}'
HYPR_MONITOR_SCALE='${monitor_scale}'
HYPR_SCALE_MODE='${scale_mode}'
HYPR_QT_X11_SCALE='${qt_x11_scale}'
HYPR_CHROME_DEVICE_SCALE='${chrome_scale}'
HYPR_KITTY_FONT_SIZE='${kitty_font_size}'
HYPR_KITTY_WINDOW_PADDING='${kitty_padding}'
HYPR_XFT_DPI='${xft_dpi}'
HYPR_GTK_XFT_DPI='${gtk_xft_dpi}'
HYPR_CURSOR_SIZE='${cursor_size}'
EOF

cat >"${KITTY_SCALE_CONF}" <<EOF
# Generated by SyncAppScaling.sh. Do not edit by hand.
font_size ${kitty_font_size}
window_padding_width ${kitty_padding}
EOF

update_ini_setting "${GTK3_SETTINGS}" "gtk-cursor-theme-size" "${cursor_size}"
update_ini_setting "${GTK3_SETTINGS}" "gtk-xft-dpi" "${gtk_xft_dpi}"
update_ini_setting "${GTK4_SETTINGS}" "gtk-cursor-theme-size" "${cursor_size}"
update_ini_setting "${GTK4_SETTINGS}" "gtk-xft-dpi" "${gtk_xft_dpi}"

cat >"${XRESOURCES_FILE}" <<EOF
! Generated by SyncAppScaling.sh. Do not edit by hand.
Xft.dpi: ${xft_dpi}
Xcursor.size: ${cursor_size}
EOF

export XCURSOR_SIZE="${cursor_size}"
export HYPRCURSOR_SIZE="${cursor_size}"
export HYPR_APP_SCALE="${scale}"
export HYPR_MONITOR_SCALE="${monitor_scale}"
export HYPR_SCALE_MODE="${scale_mode}"
export HYPR_QT_X11_SCALE="${qt_x11_scale}"
export HYPR_CHROME_DEVICE_SCALE="${chrome_scale}"
export HYPR_KITTY_FONT_SIZE="${kitty_font_size}"
export HYPR_KITTY_WINDOW_PADDING="${kitty_padding}"
export HYPR_XFT_DPI="${xft_dpi}"
export HYPR_GTK_XFT_DPI="${gtk_xft_dpi}"

xrdb -merge "${XRESOURCES_FILE}" >/dev/null 2>&1 || true
dbus-update-activation-environment --systemd \
  XCURSOR_SIZE="${XCURSOR_SIZE}" \
  HYPRCURSOR_SIZE="${HYPRCURSOR_SIZE}" \
  HYPR_APP_SCALE="${HYPR_APP_SCALE}" \
  HYPR_MONITOR_SCALE="${HYPR_MONITOR_SCALE}" \
  HYPR_SCALE_MODE="${HYPR_SCALE_MODE}" \
  HYPR_QT_X11_SCALE="${HYPR_QT_X11_SCALE}" \
  HYPR_CHROME_DEVICE_SCALE="${HYPR_CHROME_DEVICE_SCALE}" \
  HYPR_KITTY_FONT_SIZE="${HYPR_KITTY_FONT_SIZE}" \
  HYPR_KITTY_WINDOW_PADDING="${HYPR_KITTY_WINDOW_PADDING}" \
  HYPR_XFT_DPI="${HYPR_XFT_DPI}" \
  HYPR_GTK_XFT_DPI="${HYPR_GTK_XFT_DPI}" >/dev/null 2>&1 || true
systemctl --user import-environment \
  XCURSOR_SIZE \
  HYPRCURSOR_SIZE \
  HYPR_APP_SCALE \
  HYPR_MONITOR_SCALE \
  HYPR_SCALE_MODE \
  HYPR_QT_X11_SCALE \
  HYPR_CHROME_DEVICE_SCALE \
  HYPR_KITTY_FONT_SIZE \
  HYPR_KITTY_WINDOW_PADDING \
  HYPR_XFT_DPI \
  HYPR_GTK_XFT_DPI >/dev/null 2>&1 || true

hyprctl setcursor "${HYPRCURSOR_THEME}" "${cursor_size}" >/dev/null 2>&1 || true

if pgrep -x kitty >/dev/null 2>&1; then
  pkill -USR1 -x kitty >/dev/null 2>&1 || true
fi

log "scale=${scale} monitor_scale=${monitor_scale} mode=${scale_mode} qt_x11=${qt_x11_scale} chrome=${chrome_scale} kitty_font=${kitty_font_size} kitty_padding=${kitty_padding} xft_dpi=${xft_dpi} gtk_xft_dpi=${gtk_xft_dpi} cursor=${cursor_size}"

if command -v notify-send >/dev/null 2>&1; then
  notify-send \
    -a Hyprland \
    -h string:x-canonical-private-synchronous:hypr-app-scaling \
    "App scaling synced" \
    "scale ${scale} | kitty ${kitty_font_size}pt | Chrome ${chrome_scale}x | Qt ${qt_x11_scale}x" >/dev/null 2>&1 || true
fi
