# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #BBECF9
background         #161818
cursor             #67848D

active_tab_foreground     #161818
active_tab_background     #BBECF9
inactive_tab_foreground   #BBECF9
inactive_tab_background   #161818

active_border_color   #BBECF9
inactive_border_color #161818
bell_border_color     #444B4D

color0      #404243
color1		#444B4D
color2		#444B4D
color3		#3C78AE
color4		#3C78AE
color5		#3F89B4
color6		#2E96B2
color7		#96DBEE
color8		#6999A6
color9		#485053
color10		#485053
color11		#3387D2
color12		#3387D2
color13		#1A93D9
color14		#3EC8ED
color15		#96DBEE
