# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121212)
$foreground = rgb(E4C9AA)
$color0 = rgb(3C3C3C)
$color1 = rgb(464645)
$color2 = rgb(4C6065)
$color3 = rgb(4C6065)
$color4 = rgb(4C6065)
$color5 = rgb(775345)
$color6 = rgb(A17440)
$color7 = rgb(D0A97D)
$color8 = rgb(927657)
$color9 = rgb(4A4A49)
$color10 = rgb(526D74)
$color11 = rgb(526D74)
$color12 = rgb(526D74)
$color13 = rgb(8C5C48)
$color14 = rgb(B66C17)
$color15 = rgb(D0A97D)
