# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161818)
$foreground = rgb(BBECF9)
$color0 = rgb(404243)
$color1 = rgb(444B4D)
$color2 = rgb(444B4D)
$color3 = rgb(3C78AE)
$color4 = rgb(3C78AE)
$color5 = rgb(3F89B4)
$color6 = rgb(2E96B2)
$color7 = rgb(96DBEE)
$color8 = rgb(6999A6)
$color9 = rgb(485053)
$color10 = rgb(485053)
$color11 = rgb(3387D2)
$color12 = rgb(3387D2)
$color13 = rgb(1A93D9)
$color14 = rgb(3EC8ED)
$color15 = rgb(96DBEE)
