--disable-gpu
--disable-gpu-compositing
--disable-accelerated-video-decode
--disable-features=UseChromeOSDirectVideoDecoder,UseSkiaRenderer
--ozone-platform=x11
--disable-web-security
--disable-features=OutOfBlinkCors
